site_name: HostDoc 📖
site_url: https://jerewergez.github.io/HostDoc/
repo_url: https://github.com/Jerewergez/HostDoc

docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.tabs
    - search.suggest
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
