site_name: HostDoc 📖
site_description: Biblioteca personal de apuntes técnicos
site_url: https://jerewergez.github.io/HostDoc/
repo_url: https://github.com/Jerewergez/HostDoc

docs_dir: docs
site_dir: site

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - pymdownx.emoji

nav:
  - Inicio: index.md
  - Apuntes:
    - estudio/index.md
  - Proyectos:
    - proyectos/index.md
    - Arquitectura Medallón: proyectos/airflow-dbt.md
  - Arquitectura:
    - arquitectura/index.md
  - Wiki:
    - wiki/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Jerewergez/HostDoc
